### ISSUE TITLE
Setup testing

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#1]

**Comment by gavin-norman-sociomantic** [comment]
Assigned @leandro-lucarella-sociomantic, but feel free to reassign if someone else can do this.

**Comment by nemanja-boric-sociomantic** [comment]
I'm happy to provide a PR as soon as we have a branch to submit it against :-)

**Comment by nemanja-boric-sociomantic** [comment]
Done: https://travis-ci.org/sociomantic-tsunami/swarm/branches
