### ISSUE TITLE
Investigate whether suppressing of SIGPIPE can be avoided

### ISSUE THREAD

**Issue by gautam-kotian-sociomantic** [sociomantic-tsunami/swarm#10]
Swarm-neo suppresses the SIGPIPE signal here:
https://github.com/sociomantic/swarm/blob/2df46475b0719307706db68f20d7af72a96392b9/src/swarm/neo/protocol/socket/MessageSender.d#L57-L64

But this then requires applications which produce output that may be piped to other programs to explicitly catch SIGPIPE and exit.

**Comment by gautam-kotian-sociomantic** [comment]
On slack, @david-eckardt-sociomantic hinted that this may be possible.

```
[2017-04-28 13:21] David Eckardt
a quick look reveals that we could probably replace `writev(2)` with `sendmsg(2)` there,
and `sendmsg` allows suppressing `SIGPIPE`, so we wouldn't need to ignore it
```

**Comment by nemanja-boric-sociomantic** [comment]
It's already being in progress. See #9

**Comment by nemanja-boric-sociomantic** [comment]
Specifically, this file: https://github.com/sociomantic-tsunami/swarm/pull/9/commits/9e36bf357f143ec49a5de0f9832f7b2b7349b233#diff-adb75301e407f1aa91acf9c69e92fed9

**Comment by nemanja-boric-sociomantic** [comment]
And finally #11 :-)

**Comment by gautam-kotian-sociomantic** [comment]
Good to know. Feel free to close as duplicate if that's appropriate.

**Comment by nemanja-boric-sociomantic** [comment]
Fixed in https://github.com/sociomantic-tsunami/swarm/commit/fc57af9d6235174a2b7773f12aed5bf13bebb6aa
