### ISSUE TITLE
[Neo] ConnectionError notification exception is missing file and line information.

### ISSUE THREAD

**Issue by scott-gibson-sociomantic** [sociomantic-tsunami/swarm#120]
When using the NotificationFormatter output for the following code, i noticed that the log error showed `@ :0`

```
    private void connNotifier ( DhtClient.Neo.DhtConnNotification info )
    {
        auto message = formatNotification(info, this.notification_buffer);
        with ( info.Active ) switch ( info.active )
        {
            case connected:
            case hash_range_queried:
                this.log.info(message);
                break;
            default:
                this.log.error(message);
        }
    }
```

`<connection_error>: Exception 'ConnectProtocol: finalized' @ :0 occurred in the client while handling the request on node [127, 0, 0, 1]:9999`

**Comment by gavin-norman-sociomantic** [comment]
https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/protocol/connect/ConnectProtocol.d#L523

**Comment by gavin-norman-sociomantic** [comment]
Put in the next minor release, as this is not an important bug fix.
