### ISSUE TITLE
Wrong notification constants in neo readme

### ISSUE THREAD

**Issue by andrej-mitrovic-sociomantic** [sociomantic-tsunami/swarm#151]
https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/README_client_neo.rst#error-handling-and-request-notification

`info.Active.success` and `info.Active.error` do not exist (for example, for GetRange in neo), as can be seen [here](https://github.com/sociomantic-tsunami/dlsproto/blob/8c73dec7c2975524ba9dfad51dadd48ba1eeb4eb/src/dlsproto/client/request/GetRange.d#L91). Maybe this was copy-pasted from the non-neo readme? Or is it referring to other requests that still have these?

**Comment by nemanja-boric-sociomantic** [comment]
> A typical notification delegate looks something like this _imaginary_ example:

Every request type now defines its own notification union type, so there's no common base for all the notification unions.

**Comment by gavin-norman-sociomantic** [comment]
Yes, this is mentioned in the [previous section](https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/README_client_neo.rst#id12):
>Request API modules typically contain:
>* A type alias for the notification delegate.
>* The definition of the smart-union and arguments struct which are passed to the notification delegate.
>* The request's controller interface, if applicable (see below).

**Comment by andrej-mitrovic-sociomantic** [comment]
Ok, feel free to close.

**Comment by gavin-norman-sociomantic** [comment]
Thanks for checking with us though!
