### ISSUE TITLE
Disallow resuming fiber in EventDispatcher.nextEvent if not explicitly asked

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/swarm#154]
`EventDispatcher.nextEvent` accepts the flags, such as `Receive`, which will make `nextEvent` not throw an exception if the fiber is resumed with the data received - the default behavior is to allow resuming fiber for the reasons explicitly specified in the `nextEvent` call.

This behavior allows caller not to check the reason why the fiber was resumed - except in one case: the `nextEvent` will always allow explicit resume from the code with the positive resume code. This in turn makes user always to check that the resume reason is not explicit resume (with positive resume code). As this is allowed on relatively rare occasions, it seems that it might be better if the user would explicitly allow resuming the fiber (with another `NextEventFlag`).

Since this is breaking change (the behavior will change if you don't pass the flag everywhere), targeting next major.

**Comment by gavin-norman-sociomantic** [comment]
Fixed by #231.
