### ISSUE TITLE
Implement new record batcher

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#158]
The old record batcher is convenient but too rigid. We can discuss features for a replacement here.
* It should support records with fields of any type. (The old one just supports records of `<char[]>` and `<char[], char[]>`.)
* It should provide a method to get the batched size of a record. (The old one has this function internally, but it's private.)
* Compression should be optional.
* The maximum batch size (== the record size limit) should be soft and configurable at runtime, not a compile-time constant. This way, the size limit could be set in the node's config file, which could then be re-parsed if the limit needed to be changed. Future batches would then use the new size limit.
* Instead of checking that each added record fits in the remaining space in the batch, check that the size of each added record is <= the maximum batch size. This will lead to flexible sized batches of at most 2x the maximum size. (For the advantage of this approach, see https://github.com/sociomantic-tsunami/swarm/issues/158#issuecomment-339671247.)

**Comment by gavin-norman-sociomantic** [comment]
* It should support records with fields of any type. (The old one just supports records of `<char[]>` and `<char[], char[]>`.)

**Comment by gavin-norman-sociomantic** [comment]
* It should provide a method to get the batched size of a record. (The old one has this function internally, but it's private.)

**Comment by nemanja-boric-sociomantic** [comment]
Perhaps it should have concept of the piggy backing the control messages? Not sure how useful that would be, but in case node needs to signal something to the client before the client goes to process the batch, instead of sending the separate message it could stuck it there. 

Really, only problems I had with the `RecordBatcher` are:

- Too restricted `add()` API (I had the case where the keys were `time_t`).
- Get the batched size of the record
- I can't remember if the compression was optional or not, but I recall I had the use case for sending uncompressed data (i.e. does batcher provides other means of getting the internal data than `compress`?)

Perhaps the API could be a bit different: I think this is our usual use-case for the batching the record: https://github.com/sociomantic-tsunami/dlsproto/blob/3f9876ef509047eb5f71b145f125fb5e6d8fdbad/src/dlsproto/node/request/model/CompressedBatch.d#L128-L152

Maybe this entire `switch` could be made more elegant now we have a chance.

**Comment by gavin-norman-sociomantic** [comment]
Good idea about optional compression. (I'm adding features into the issue description.)

**Comment by gavin-norman-sociomantic** [comment]
>Perhaps the API could be a bit different: I think this is our usual use-case for the batching the record: https://github.com/sociomantic-tsunami/dlsproto/blob/3f9876ef509047eb5f71b145f125fb5e6d8fdbad/src/dlsproto/node/request/model/CompressedBatch.d#L128-L152

One idea would be to use delegates, like this:
```D
this.batcher.add(record, &this.sendBatch);
```
I'm not sure about the too-big record handling. Should we have some default approach? (e.g. discard, send individually...?)

**Comment by david-eckardt-sociomantic** [comment]
A bold suggestion: Change the batch size policy to not enforce the maximum batch size. Instead, enforce that the size of a record is at most the batch size and append records to the batch until the batch size is equal or greater than the target size, then consider the batch to be complete.
Enforcing the batch size to be at most the target size is problematic in a DMQ node: If a record is popped from the storage and doesn't fit in the batch then the node has to store it somewhere for the next batch. This complication can bed avoided, nothing in our system breaks if the target batch size is moderately exceeded. With the new policy the worst case would be a batch with almost twice the target size. This soft limit policy also simplifies the calculation if a record plus its metadata -- the size and potentially a key -- would fit in the batch by just ignoring the insignificant metadata size overhead.

I also suggest separating the code to create a batch from the code parsing it. Usually (always?) a program either creates or parses a batch, rarely does it need to do both in one place.

**Comment by gavin-norman-sociomantic** [comment]
Sounds good.

>I also suggest separating the code to create a batch from the code parsing it. Usually (always?) a program either creates or parses a batch, rarely does it need to do both in one place.

The existing module is exactly like that...?

**Comment by david-eckardt-sociomantic** [comment]
> The existing module is exactly like that...?

Oh, is it? :blush:

**Comment by gavin-norman-sociomantic** [comment]
Yes. There's `RecordBatch` (receiver) and `RecordBatcher` (generator).

**Comment by david-eckardt-sociomantic** [comment]
Right, but I would even prefer to put it in separate modules.

**Comment by gavin-norman-sociomantic** [comment]
Any strong reason to do so? It seems like an extremely minor point to discuss at this juncture. (Unless I'm missing some important point?)

**Comment by david-eckardt-sociomantic** [comment]
Not a strong point, we can discuss it later.

**Comment by gavin-norman-sociomantic** [comment]
The maximum batch size (== the record size limit) should be soft and configurable at runtime, not a compile-time constant. This way, the size limit could be set in the node's config file, which could then be re-parsed if the limit needed to be changed. Future batches would then use the new size limit.

**Comment by gavin-norman-sociomantic** [comment]
>Enforcing the batch size to be at most the target size is problematic in a DMQ node: If a record is popped from the storage and doesn't fit in the batch then the node has to store it somewhere for the next batch.

@david-eckardt-sociomantic this makes me think. What happens in the DMQ node if a record is popped that is bigger than the batch's size limit? Is the record discarded? (It essentially can't be handled.)
