### ISSUE TITLE
Add v4.5.0 to LibFeatures

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#163]

**Comment by mathias-lang-sociomantic** [comment]
IMO this should happen right after a release.
E.g. release v4.4.0 => Commit to clear `relnotes` => Commit to add v4.5.0 to LibFeatures.
So it can already be done.

**Comment by gavin-norman-sociomantic** [comment]
Well, it can be done any time before the release of v4.5.0, including now.
