### ISSUE TITLE
Modify RequestEventDispatcher for use as a simple struct (not pooled)

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/swarm#186]
From https://github.com/sociomantic-tsunami/dlsproto/pull/39

> For the future: It occurs to me that we might be able to adapt RequestEventDispatcher to accept void[]s to use internally, doing away with the need to have a separate pool of them. (I think the only thing it contains that should be reused is a couple of arrays.)

If the `RequestEventDispatcher` were to accept the required resources via an initialiser, it would not do any heap allocation internally, and would thus need to be stored in a pool.

**Comment by gavin-norman-sociomantic** [comment]
Fixed by #230.
