### ISSUE TITLE
Storage class' `id` method should return a `cstring`

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#187]
There's no need for it to be mutable.

**Comment by david-eckardt-sociomantic** [comment]
https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/node/storage/model/IStorageEngine.d#L141

This is already the case. (dmqnode overrode it returning `char[]`.)

**Comment by gavin-norman-sociomantic** [comment]
Ah ok, so the error was purely in dmqnode :+1:
