### ISSUE TITLE
Ensure Swarm works with the breaking changes in v4.0.0.alpha3

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/swarm#190]
Two breaking changes affect swarm at the moment:

- `Flexible*Queue` returning `void[]` instead of `ubyte[]` (looks like just casting on return will be enough)
- `NeoNode`'s `ConnectionHandler` needs to implement `unregisterSocket`.

**Comment by gavin-norman-sociomantic** [comment]
Done in https://github.com/sociomantic-tsunami/swarm/pull/191.
