### ISSUE TITLE
Wrong Listeners iteration if removing listener

### ISSUE THREAD

**Issue by david-eckardt-sociomantic** [sociomantic-tsunami/swarm#20]
The following situation happens in a swarm neo application, but could happen with classic swarm, too:
- A channel with two listeners is removed.
- `IListeners.trigger` is called with `Listener.Code.Finish`.
- `IListeners.trigger_` iterates over `ListenerSet`, which iterates over `ListenerSet.listeners`, a dynamic array of the registered listeners.
- Iterate over `listener = ListenerSet.listeners[0]`, call `listener.trigger`.
- `listener.trigger` suspends the currently running fiber A.
- Another fiber B removes this listener, calling `ListenerSet.remove`.
- `ListenerSet.remove` moves the removed listener to the end of the array. Because there are only two listeners registered it swaps the two listeners in the array.
- `ListenerSet.remove` returns.
- Fiber B is suspended, fiber A is resumed.
- The iteration continues with `listener = ListenerSet.listeners[1]`. Because `ListenerSet.remove` swapped the two array elements this is now the same object as in the first iteration cycle, the listener that was just unregistered.

Result: One listener is triggered a second time after it has been removed, the other is not triggered at all. Even without a fiber race condition this could happen if `Listener.trigger` calls `ListenerSet.remove`.

I'm working on a bug fix to allow for removing a listener during an iteration.

**Comment by gavin-norman-sociomantic** [comment]
Nasty. If this is at the core (i.e. shared legacy/neo) level, we could think about fixing this in v2.6.x.

**Comment by gavin-norman-sociomantic** [comment]
@david-eckardt-sociomantic this was fixed, right?

**Comment by david-eckardt-sociomantic** [comment]
Fixed in #855.
