### ISSUE TITLE
Convert `assert` to `verify`

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#200]

**Comment by gavin-norman-sociomantic** [comment]
There's a total of 572 asserts in `src`. Splitting them up into the following chunks seems manageable:
* `neo/client` (206) (https://github.com/sociomantic-tsunami/swarm/pull/201 reduces this number by 82)
* Everything else in `neo` (238) https://github.com/sociomantic-tsunami/swarm/pull/241
* Everything not in `neo` (128)

**Comment by gavin-norman-sociomantic** [comment]
Guidelines: https://github.com/sociomantic-tsunami/sociomantic/blob/master/Code/D/assert-vs-enforce.md#guidelines

**Comment by gavin-norman-sociomantic** [comment]
This can only be done in the next major, as `verify` was added in ocean v3.4.x and swarm is using v3.1.x.

**Comment by gavin-norman-sociomantic** [comment]
As @david-eckardt-sociomantic wrote #201, the honour of continuing with `neo.client` goes to him.

I'll tackle the rest of `neo`.

@nemanja-boric-sociomantic could you tackle everything not in `neo`?

**Comment by nemanja-boric-sociomantic** [comment]
Yes.

**Comment by nemanja-boric-sociomantic** [comment]
This is done in #241 #246 and #249
