### ISSUE TITLE
Make request handler functions nothrow?

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#213]
The intention is to force them to handle any exceptions thrown internally.

**Comment by mathias-lang-sociomantic** [comment]
Won't we have to wait until we drop D1 support though ? CC @mihails-strasuns-sociomantic

**Comment by gavin-norman-sociomantic** [comment]
My idea was that we can use the D2 compiler to enforce this.

**Comment by gavin-norman-sociomantic** [comment]
This would be similar to our use of `final switch`. It has no effect in D1 builds, but allows us to enforce certain checks in the D2 build.

**Comment by mathias-lang-sociomantic** [comment]
I see what you want to do, and get the motivation. I know @mihails-strasuns-sociomantic had some concerns, which is exactly the reason a whitelist of injections was implemented in `d1to2fix`.
The bottom line was, AFAIR, "Don't use D2-specific features unless *required*" (e.g. by the runtime).
But again, I'm just the messenger.

**Comment by gavin-norman-sociomantic** [comment]
>The bottom line was, AFAIR, "Don't use D2-specific features unless required" (e.g. by the runtime).

Yeah, this would be a slight divergence from that principle. I think it's worth discussing, though, as it seems that nothrow is really what we want here. (And this is something that's actually come up in practice in the live system.)

**Comment by mihails-strasuns-sociomantic** [comment]
Yes, I think `final switch` example was a good confirmation that all concerns have been valid and would object making any further experiments in that direction unless necessary until D1 is gone.

**Comment by gavin-norman-sociomantic** [comment]
Wasn't the problem with usage of `final switch` due to fact that it required a new D1 compiler version? In the case of `nothrow`, I would imagine we'd just do it via a d1to2fix injection.

**Comment by mihails-strasuns-sociomantic** [comment]
That would still require new `d1to2fix` version - and new swarm major to actually enable that. All for a questionable gain.

**Comment by gavin-norman-sociomantic** [comment]
Well, this issue is in the v5.0.0 milestone for a reason ;)

The gain isn't earth shattering, but it would definitely be a help if the compiler could enforce our requirement here. It's just down to human virtue / memory, otherwise (which is notoriously unreliable).

**Comment by mihails-strasuns-sociomantic** [comment]
Yes, the same argument was for the `final switch`. I don't question that there is some benefit, but so far experience shows that benefit has to be exactly earth shattering to justify extra infra pressure. We have just too many infra migration topics on our table to be able casually throw in few more.

You could  implement this as runtime check/warning for now or just keep in mind until D2 days.

**Comment by gavin-norman-sociomantic** [comment]
Yeah, fair enough. Was just a thought.

**Comment by gavin-norman-sociomantic** [comment]
Closed in favour of #214, for now.
