### ISSUE TITLE
Catch and log exceptions thrown from node request handlers

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#214]
#213 discussed the idea of actually making them nothrow, in D2 builds. The conclusion was that we don't want to go down the road of adding extra dev-infra requirements (i.e. a new version of `d1to2fix`) right now, so we will have to keep relying on developer virtue / memory, for the time being.

To support those notoriously unreliable qualities, we can at least add a run-time check at the point where the request handler function is called.

**Comment by gavin-norman-sociomantic** [comment]
Oh. Exactly like this: https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/node/ConnectionHandler.d#L447-L458

**Comment by nemanja-boric-sociomantic** [comment]
The problem with this is that it just logs the exception, but then rethrows it. Being a regular exception, this will just terminate the fiber, but the connection will not be aware of it, hanging the request forever.

Proposals:

- Throw the `AssertException` (in D1) or `Error` (in D2) .
- Use `assert(false)` and later replace it with `verify(false)` and adapt `swarm.util.MessageFiber` to rethrow `SanityException`s as well as `Error`s.

**Comment by gavin-norman-sociomantic** [comment]
>Throw the AssertException (in D1) or Error (in D2) .

`MessageFiber` has special handling of `Error` (D2) and `AssertError` (D1) (https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/util/MessageFiber.d#L53-L60) I'm not sure where `AssertError` comes from...

**Comment by nemanja-boric-sociomantic** [comment]
Sorry, `s/AssertException/AssertError` in my response: https://github.com/sociomantic-tsunami/tangort/blob/9fb5b8bf1960eae04d31a689bba0cec3116fce5d/src/core/exception.d#L175

That's the only D1 equivalent of the `Error` class in D2 that I'm aware of.

**Comment by gavin-norman-sociomantic** [comment]
Ahh ok, the runtime. I also thought the runtime class was `AssertException`, so assumed `AssertError` must be something else.

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, me too. I guess it got renamed at some point.

**Comment by gavin-norman-sociomantic** [comment]
Maybe to bring it in line with D2.

**Comment by gavin-norman-sociomantic** [comment]
We decided to not do anything here. The current code logs an error if a handler throws, and in the absence of being able to strictly enforce that they cannot, doing anything else here is a potentially surprising behavioural change. It's easy to notice these cases when testing (by user reports / checking the log), so for now we'll just leave this down to developer virtue.
