### ISSUE TITLE
Handling of I/O exceptions in node request handlers

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#216]
As discussed in #213 and #214, it is proposed to make sure node request handlers catch all exceptions and notify the client that there was an error. (i.e. request handlers should never throw.) (See below for reasoning.)

_But_ what happens if the exception thrown in the node request handler is an I/O exception on socket access?

(The reason for not allowing request handlers to throw is the way exceptions that are thrown out of request handlers are handled. Currently, the exception will be [logged and rethrown](https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/node/ConnectionHandler.d#L447-L458) and will end up being handled by `MessageFiber.resume()`(https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/util/MessageFiber.d#L589-L618). The exact handling here depends what type the exception is. `AssertError`s (or `Error`s generally, in D2) will be rethrown in the calling context (i.e. in the fiber that called `resume()` on the fiber that threw), but other exceptions are ignored at this stage, meaning that the request-on-conn fiber (where the handler is running) exits without being able to notify the client of what's happened. The request on the client side thus just hangs.)

**Comment by nemanja-boric-sociomantic** [comment]
As noted in #251, when catching the exceptions in the `RequestOnConn`'s handler, `IOError`s (the type thrown from `Message*Loop`) should not be caught, but they should be allowed to kill the `RequestOnConn` fiber (as the `RequestOnConn` fiber will be notified by the `Connection` fiber).

However, getting to the point of catching the exceptions and informing the client about errors is not trivial, and it requires the detailed design of both client and the node side. That's covered by the issue #251, and it's mentioned there that the `IOError`s should be left to kill the fiber, so I'm closing this one.
