### ISSUE TITLE
Neo Config should not require a nodes file to be specified

### ISSUE THREAD

**Issue by don-clugston-sociomantic** [sociomantic-tsunami/swarm#228]
In `swarm.neo.client.mixins.ClientCore`, both `nodes_file` and `credentials_file` are listed as `Required!(istring)`.

This is problematic for apps which do not always create the corresponding swarm client. For example, some apps may have a test mode where they do not produce any DMQ output. Others normally read from a DMQ channel, but may optionally read from a DLS. This may be specified either by a command-line argument, or by another config setting. In all of these cases, no constructor is ever called.

But because these fields are required, there are two options, both very unattractive:
(a) Do not use the `ConfigParser`.
(b) Specify dummy values in the config file, which are meaningless and will never be used.

I'm using the second option, creating a section which is never used, and has `nodes_file=/dev/null`.

Even in the case where the app always created the swarm client, the behaviour still seems wrong, because there the clients have an `addNodes` function.

I think these values should really be checked in the constructor of the Neo clients, not in the config parser.

Incidentally, if these values are not specified, the behaviour is dreadful. Instead of a nice error message, it vomits a stack trace. Though I think that's the fault of ocean, not swarm.

**Comment by gavin-norman-sociomantic** [comment]
>Even in the case where the app always created the swarm client, the behaviour still seems wrong, because there the clients have an addNodes function.

The idea is that `addNodes` will probably be removed at some point.

**Comment by gavin-norman-sociomantic** [comment]
Maybe I'm missing something. If you're not planning to instantiate a client, why do you even parse the client config from your config file?

**Comment by don-clugston-sociomantic** [comment]
Because it's not known if the client will be instantiated until the config file has been parsed.

**Comment by gavin-norman-sociomantic** [comment]
Sure, but can't you do something like:
```D
void parseConfig ( )
{
  auto app_config = parseTopLevelConfig();
  if ( app_config.use_dmq )
  {
    auto dmq_config = parseDmqConfig();
    auto client = new DmqClient(dmq_config, ...);
  }
}
```
?

**Comment by don-clugston-sociomantic** [comment]
Not really. The parser is called from the framework in `DaemonApp.processConfig`, and that's much too early.
By the time that we're ready to create swarm clients, we don't have access to the `ConfigParser`.
In some cases, something like may be possible (I called that option(a) above) but in general it's quite ugly.
The framework assumes that the config file is parsed before the app really starts doing anything. I think that's not unreasonable.

**Comment by gavin-norman-sociomantic** [comment]
Sure, wouldn't something like this work?
```D
class MyApp : DaemonApp
{
  private AppConfig app_config;
  private ClientConfig dmq_config;
  private DmqClient dmq;

  public override void processConfig ( IApplication app, ConfigParser config )
  {
    ConfigReader.fill("App", this.app_config, config);
    if ( this.app_config.use_dmq )
      ConfigReader.fill("DMQ", this.dmq_config, config);
  }

  override protected int run ( Arguments args, ConfigParser config )
  {
    if ( this.app_config.use_dmq )
    {
      assert(this.dmq_config !is null);
      this.dmq = new DmqClient(this.dmq_config, ...);
    }
  }
```

**Comment by don-clugston-sociomantic** [comment]
The behaviour may be specified by a command-line argument, and the logic may be more complicated than just a simple bool. Note that in that example you've given, `this.dmq_config` was not initialized. So it all gets quite messy.

I actually have cases where the value for `enable` is part of the same config struct (it's derived from the DMQ `Config`). Ie, it has:
```d
bool enabled
string channel_name
string nodes_file
string credentials_file
```
where if output is disabled, the other values are not required.

**Comment by gavin-norman-sociomantic** [comment]
>The behaviour may be specified by a command-line argument

Command line arg parsing happens before config parsing. (See https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/app/ext/ConfigExt.d#L123-L124.)

>Note that in that example you've given, this.dmq_config was not initialized.

Yes it is. Line 11.

>I actually have cases where the value for enable is part of the same config struct

It would be simple enough to move it to another config category, though.

My point, generally, is that (as far as I can see) this isn't a _required_ library feature. I'd prefer applications with unusual cases like this to adapt to the way the library works, rather than adding support for unusual cases to the library.

**Comment by don-clugston-sociomantic** [comment]
> Command line arg parsing happens before config parsing

It's a completely different part of the app. I don't have anywhere in my code where both are present.

>>    Note that in that example you've given, this.dmq_config was not initialized.
> Yes it is. Line 11.

Not in the case where it was disabled.

>>    I actually have cases where the value for enable is part of the same config struct
> It would be simple enough to move it to another config category, though.

At the expense of a very ugly config file format. The library limitations should not be affecting the config file format. It indicates an extremely inflexible library. And it's completely unnecessary. Just remove the `Required` from the definition in the Config, and move that check to the constructor, where it belongs --- first check that the file is specified, then check that it exists, then check that its contents are valid.
Simple.

**Comment by gavin-norman-sociomantic** [comment]
>Not in the case where it was disabled.

Right. That's precisely the point. If the config specifies that the DMQ client is disabled, the DMQ client config is not parsed at all.

I'm of the opinion that swarm is correct. If you're parsing the client's config from a config file, then the path to the nodes file is required. Anything else just seems like an application level workaround leaking into a library.

**Comment by gavin-norman-sociomantic** [comment]
(I have requested outside opinions to get more perspective.)

**Comment by don-clugston-sociomantic** [comment]
To be clear: When converting to Neo, I had to make this change:

```d
[OUTPUT]
 enable_dmq_output = false
+nodes_file = /dev/null
+credentials_file = /dev/null
```
There were no other related changes, just this one.

**Comment by gavin-norman-sociomantic** [comment]
>The idea is that `addNodes` will probably be removed at some point.

I was wrong about that. It will still be required for the constructor that is intended to be used in tests: https://github.com/sociomantic-tsunami/swarm/blob/v5.x.x/src/swarm/neo/client/mixins/ClientCore.d#L110-L125

**Comment by gavin-norman-sociomantic** [comment]
Closing. I don't see this as a library issue, and no other swarm maintainers have come forward in defense of this issue.
