### ISSUE TITLE
Remove versioned code from Reopenable ClientStats test.

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/swarm#252]
The ClientStats/ReopenableFilesExt integration tests contains the `static if (hasFeatures!(ocean, 3, 6))` branch to use `ReopenablerFilesExt.reopenFile` method which exists from ocean v3.6.0. This is needed as the v4.x.x major of swarm supports it. This can be removed in swarm v5.0.0.

**Comment by gavin-norman-sociomantic** [comment]
(Due to the inclusion of the keyword "deprecated", this will be caught in #235 ;)

**Comment by nemanja-boric-sociomantic** [comment]
Fixed in #252.
