### ISSUE TITLE
Try adding verify to swarm (copy from ocean)

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#286]
This will enable us to use `verify` in v4.x.x already, rather than having to continue using `assert` and risk forgetting to convert them into `verify`s when merging into v5.x.x.

**Comment by nemanja-boric-sociomantic** [comment]
I suggest we implement this by making the simple verify method that if `hasFeaturesFrom("ocean", 3, 4)` passes it forwards the call to the ocean's `verify`. On the other hand it should then declare and throw its `SanityException`. Problem with copying the code is that you'll get two different `SanityException` classes and that the user code (if not just doing `catch (Exception)`) will always catch the ocean's one.
