### ISSUE TITLE
Implement ClientCore.abortAllRequests

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/swarm#328]
There's a unimplemented method inside the `ClientCore`: `abortAllRequests` which should abort all requests and run their finished notifier.

This can be then used for the `abort/reconnect` pattern where all requests are finished and the nodes are informed that requests no longer exist by dropping the connection from the client - something that's necessary if the requests support auto-reconnect. 

The implementation should be as easy as going through the request set and calling `abort` on the individual requests.

https://github.com/sociomantic-tsunami/swarm/blob/b3209ee3abcfd737302b099c8ff6fdb333957abf/src/swarm/neo/client/mixins/ClientCore.d#L858

**Comment by gavin-norman-sociomantic** [comment]
Not needed right now, closing. We can reopen if it's needed at some point.
