### ISSUE TITLE
Deprecate non-scoped controller access

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#368]
All usage of the request controllers should go via the client's `control` method ([internal implementation](https://github.com/sociomantic-tsunami/swarm/blob/v5.x.x/src/swarm/neo/client/mixins/ClientCore.d#L859-L873)).

I believe the whole `swarm.neo.client.mixins.Controllers` module can be deprecated.

**Comment by gavin-norman-sociomantic** [comment]
(The only known usage of the non-scoped controller objects is for use with ocean's throttler. This is to be replaced with #369.)

**Comment by gavin-norman-sociomantic** [comment]
Blocked on implementation of #369.

**Comment by matthias-wende-sociomantic** [comment]
This is irrelevant due to https://github.com/sociomantic-tsunami/swarm/issues/391.
