### ISSUE TITLE
Add new throttler / stream processor for use with neo clients

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#369]
The throttler should internally track the ids of the controlled requests.

**Comment by gavin-norman-sociomantic** [comment]
See #370 for reasons why this is needed.

**Comment by matthias-wende-sociomantic** [comment]
I think we are going another path https://github.com/sociomantic-tsunami/swarm/issues/391. Closing the issue!
