### ISSUE TITLE
Fix neo Suspendable to work with oceans ISuspendable Interface

### ISSUE THREAD

**Issue by matthias-wende-sociomantic** [sociomantic-tsunami/swarm#391]
- [ ] implement suspended in Controllers.d Suspendable template class
- [ ] release swarm 6 d2 only (this will break current implementation of getAll request)
- [ ] enhance `BatchRequestCore` (https://github.com/sociomantic-tsunami/swarm/issues/243)
- [ ] change all all nodes requests (e.g. getAll) to use `BatchRequestCore` (https://github.com/sociomantic-tsunami/dhtproto/issues/38)
- [ ] deprecate `handlePending` in `Controllers.d` `Suspendable` template class
- [ ] deprecate `SuspendableRequestCore`
- [ ] release new dhtproto with working getAll request

**Comment by gavin-norman-sociomantic** [comment]
Fixed in #394.
