### ISSUE TITLE
Add turtle v8.0.0 submodule and abstract node env extension

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#47]

**Comment by gavin-norman-sociomantic** [comment]
Actually, adding a submodule will potentially require users of swarm to change their application code (to also add the submodule or to update it to the required version). This means this can't be done in a minor release.

Given the triviality of the second part of this issue ("implement node env"), it's not worth making a major swarm release for this. Closing.

**Comment by mihails-strasuns-sociomantic** [comment]
IMHO it is worth keeping it open in next major milestone so that this base module gets added to it once it is out

**Comment by gavin-norman-sociomantic** [comment]
Maybe I'm missing what this base class will contain. Doesn't it just have to implement the "don't log errors when unregistered by turtle" logic? If so, that's super trivial to implement in the protos and doesn't really fit in swarm (the node base classes in swarm don't do any logging).

**Comment by mihails-strasuns-sociomantic** [comment]
It contained bunch of common code between different protos : https://github.com/sociomantic/turtle/blob/v7.x.x/src/turtle/env/model/Node.d

**Comment by gavin-norman-sociomantic** [comment]
Ah that. I see.

**Comment by gavin-norman-sociomantic** [comment]
See (e.g.) https://github.com/gavin-norman-sociomantic/dhtproto/blob/23180a3fe4229062e29f1e1a3d7a1da07d45d8f0/src/turtle/env/model/Node.d.

**Comment by nemanja-boric-sociomantic** [comment]
Done in #232
