### ISSUE TITLE
Reassess swarm versioning / maintenance policy

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#48]
Swarm no longer contains concrete client classes and is thus no longer directly used by applications. It is only used indirectly via other libraries which implement concrete clients.

Thus, the set of versions of swarm that need to be maintained is defined solely by the needs of the dependent libraries. Keeping a strict, 6-month maintenance period for past major versions may not be necessary.

**Comment by leandro-lucarella-sociomantic** [comment]
But if older client implementation need older swarm, isn't the situation transitively the same as before?

**Comment by gavin-norman-sociomantic** [comment]
For bug-fixes, yes, the situation is the same as always. The difference is for new features = minor releases.

**Comment by mihails-strasuns-sociomantic** [comment]
That would make it a slight deviation of normal neptune rules. i.e. last release of major is still maintained 6 months for bug fixes but new features only go to most recent one. Only concern I have is that it may conflict with some of rules in neptune-release we may want to add normally.

**Comment by gavin-norman-sociomantic** [comment]
>Only concern I have is that it may conflict with some of rules in neptune-release we may want to add normally.

Yes, this is what I was wondering about.
