### ISSUE TITLE
Add functions to read client auth name/key from a file

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#53]
This is a common usage pattern that currently has to be implemented in user code.

**Comment by gavin-norman-sociomantic** [comment]
Will probably tie in with #52.

**Comment by joseph-wakeling-sociomantic** [comment]
As a suggestion: support both reading a key alone, and `name:key`.

**Comment by gavin-norman-sociomantic** [comment]
Hm, this makes me wonder. Maybe we could canonise (?) reading auth name & key from a credentials file and simply pass the path of that file to the client ctor.

**Comment by joseph-wakeling-sociomantic** [comment]
I like that as an option, as it strongly discourages the user from hardcoding credentials in-app, and offers an easy route for CLI apps to support neo authentication.  Then neo config options come down to `nodes_file` and `auth_file`.

I'm not sure I would make `auth_file` the _only_ option when constructing a client (a client constructor overload allowing `auth_name` and `auth_key` to be separately provided could still be a good idea).  Your call on that, though.
