### ISSUE TITLE
Ensure that pointer-types are aligned when serializing request args

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#55]
The GC scans will only find aligned addresses so if data that potentially contains a pointer is not on an aligned address, the pointer could be lost and the referenced object collected.

This is specifically the case for the legacy context union which is serialized on a 4-byte boundary (because the command code came first) at https://github.com/sociomantic/swarm/blob/master/swarm/core/client/request/params/IRequestParams.d#L326. This also applies to pointers serialized in the neo client.

The serialization should be enhanced so that it makes sure that pointer types are always aligned.

One idea was, to do it similar to the ConfigFiller, which scans a class and it's super classes for all the members. Templates could be used to add information on how to serialize a certain member (e.g. DeepCopy or ShallowCopy)

**Comment by mathias-lang-sociomantic** [comment]
You probably want to edit that link tho.

**Comment by mihails-strasuns-sociomantic** [comment]
Note that if you use ocean contiguous serializer it doesn't matter because _whole_ serialized array is always marked as `NO_SCAN` right now (https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/util/serialize/contiguous/Serializer.d#L210)

**Comment by gavin-norman-sociomantic** [comment]
Ah interesting. That changes things. Replaced with #60.
