### ISSUE TITLE
Error delegate passed to ConnectionSetupParams is overwritten in Node

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#58]
The API is unclear on this point. It _appears_ that the user (the implementer of a `Node`-derived class) has the option of passing an error delegate which will be passed through to the constructor of each connection handler in the pool. However, this delegate is ignored and is overwritten with the `Node`'s own delegate at https://github.com/sociomantic-tsunami/swarm/blob/02dfdeb7d5098fcd3e9b9602b4fc13faf78aba24/src/swarm/node/model/Node.d#L185.

The [`error_callback()`](https://github.com/sociomantic-tsunami/swarm/blob/02dfdeb7d5098fcd3e9b9602b4fc13faf78aba24/src/swarm/node/model/Node.d#L208) method can then be called at some later time to set the user's delegate again.

It's all a bit convoluted and looks like it could be tidied up.

**Comment by gavin-norman-sociomantic** [comment]
Related to #57.

**Comment by mathias-lang-sociomantic** [comment]
Those links might need some attention as well :)

**Comment by gavin-norman-sociomantic** [comment]
Thanks. Updated.

**Comment by mathias-lang-sociomantic** [comment]
@gavin-norman-sociomantic : Press `Y` to get a link to the commit. This way the link will always point to the right commit, even if the branch is gone.
