### ISSUE TITLE
Improve performance of RecordStream

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#69]
The TODO here needs to be addressed https://github.com/sociomantic-tsunami/swarm/blob/189fe416f5f327138d2b60aec0cec9dbe308b846/src/swarm/util/RecordStream.d#L216-L250

**Comment by gavin-norman-sociomantic** [comment]
@mathias-lang-sociomantic said:
>I tried to do so... It's not trivial :P
>Basically you want to read chunks. But IIUC, what we use for reading is Cin - which is a blocking stream.
So if one reads a chunk too big, it's likely that the reader would block until a new record is received. Which is, obviously, quite wrong. So it sounds like we need to get non-blocking stdin, unless I've missed another approach.

**Comment by gavin-norman-sociomantic** [comment]
@nemanja-boric-sociomantic said:
>Yeah, `stdin` is pollable (you could use `fileno(stdin)` (both from https://github.com/sociomantic-tsunami/tangort/blob/32ad03f41da038b6e315931c551ddfe4cd0d26eb/src/core/stdc/stdio.d#L158) to get the fd). It will have to be combined with the `fcntl` to add `O_NONBLOCK` to stdin as well.

**Comment by mathias-lang-sociomantic** [comment]
Links ;)

**Comment by gavin-norman-sociomantic** [comment]
Damn :D

**Comment by gavin-norman-sociomantic** [comment]
Fixed by https://github.com/sociomantic-tsunami/swarm/pull/247.
