### ISSUE TITLE
Rename `started` notification to `ready_to_control`

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/swarm#98]
Discussion with users has revealed that the name `started` is misleading. They expect this to occur strictly before data is received (which is not the case).

The notification is usually described as:
```
    /// All known nodes have either started handling the request or are not
    /// currently connected. The request may now be suspended / resumed /
    /// stopped, via the controller.
```
The second sentence is the part that is actually important, from the user's point of view.

Suggest renaming to `ready_to_control`.

This field is referenced here, and renaming it will cause a breaking change:

https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/client/mixins/AllNodesRequestCore.d#L596

**Comment by gavin-norman-sociomantic** [comment]
This is interesting. The notification is actually referred to in the all-nodes request helpers, which know nothing about controllers. (Controllers a re feature of the suspendable request helpers, built on top.) Naming the notification `ready_to_control` would seem weird, in the context in which it's used.

**Comment by gavin-norman-sociomantic** [comment]
It's likely that this issue will become defunct. The suspendable requests are planned to be replaced with batch requests.

**Comment by gavin-norman-sociomantic** [comment]
Initial testing with batch requests (DMQ Consume, DLS GetRange) shows that this is a successful technique. Closing this as it's unlikely to be needed.
